apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: masudbappy/config-server:configserver # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888 # The port that the container is running on in the cluster